### ISSUE TITLE
Rather than collapse, could it not toggle back and forth?

### ISSUE THREAD

**Issue by LaraSQP** [mrlacey/CollapseComments#10]
First of all, thank you for developing this brilliant extension.

As the title says, could it not toggle rather than just collapse? That is, could it collapse and expand?

Also, and I figure it is a stretch, could it be made to work in "Preview" mode?

Much, much appreciated.

**Comment by mrlacey** [comment]
Visual Studio already has an option to **Expand all outlining** (`ctrl+M`, `ctrl+X`) which will already expand all collapsed sections.
The built-in **Toggle all outlining** (`ctrl+M`, `ctrl+L`) will also expand collapsed sections.

I'm not saying no, I'm just trying to understand if adding this will add something that isn't already possible. Do you have scenarios where you need to expand (all) comments but not change any other sections? 

> could it be made to work in "Preview" mode?

I'm not sure what you mean by this. Could you please expand?

**Comment by LaraSQP** [comment]
Thank you. Again. You are right. I had missed those options for this purpose (i.e., **Expand all outlining** and **Toggle all outlining**).

`Preview mode` refers here (VS2019) to the opening of a file as the right-most tab in `read-only` mode to be able to peek into it. This always happens when doing a `ctrl+click` on, for example, a `LINQ` method (e.g., `First`), which opens the `Enumerable` class file for viewing.

And, btw, I have a different issue. The option `Enter outlining mode when files open` stopped working since I installed the extension (even though it is still enabled under `Text Editor->C#->Advanced` in the `Options` dialog) and I now have to do it manually every time I open a file. I have written a few extensions myself and I would be surprised if your extension has anything to do with it but it is driving me nuts and had to ask.

**Comment by mrlacey** [comment]
CLosing based on above response
