### ISSUE TITLE
How to change configuration options?

### ISSUE THREAD

**Issue by csadam** [mrlacey/CollapseComments#13]
Could you please tell where can I change these options?
- collapse (or expand) using/import directives
- auto-collapse when opening a file

I can't find any documentation about this.

**Comment by mrlacey** [comment]
Go to **Tools > Options... > Collapse Comments**

![Tools menu showing 'Options...' option](https://user-images.githubusercontent.com/189547/88825546-9fe89500-d1bf-11ea-8b16-54057bfb449f.png)


![The Collapse Comments page in the options dialog](https://user-images.githubusercontent.com/189547/88825375-64e66180-d1bf-11ea-8cce-9231ddbdf19d.png)
