### ISSUE TITLE
Collapse to Comments (Ctrl+M, Ctrl+C) not working as expected when 'Collapse to definition' is used

### ISSUE THREAD

**Issue by SridharPasham** [mrlacey/CollapseComments#14]
### Installed product versions
- Visual Studio: 2019 Enterprise, 16.7.0
- This extension: 1.9

### Description
Collapse to Comments (Ctrl+M, Ctrl+C) not working as expected when 'Collapse to definition' is used

### Steps to recreate
1. Outlining -> Collapse to definition (Ctrl+M,O)
2. Outlining -> Collapse to Comments (Ctrl+M, Ctrl+C)

### Current behavior
Nothing happens

### Expected behavior
Collapse to Comments (Ctrl+M, Ctrl+C) should collapse comments and expand method definitions.

**Comment by mrlacey** [comment]
This is a misunderstanding in the expectation of behavior.

The command is "Collapse Comments" not "Collapse **to** Comments"
The intention is that this command simply operates to collapse comments and does not act as a toggle.

Visual Studio has lots of commands relating to expanding and collapsing outlining. This extension was meant to fill a very specific gap.

If you want comments collapsed and everything else expanded, I suggest you use:
1. Expand all (`Ctrl+M`, `Ctrl+X`)
and then 
2. Collapse Comments  (`Ctrl+M`, `Ctrl+C`)


There is also a `Toggle All Outlining` command (`Ctrl+M`, `Ctrl+L`) that may also be useful.
