### ISSUE TITLE
Add support for VS2022

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/CollapseComments#18]

**Comment by ironcev** [comment]
Hi @mrlacey, thanks for all your efforts on Collapse Comments! I love the extension and realized that I am seriously missing it in VS2022 :-) Do you plan to add VS2022 support anytime soon? If you think it will take a while I could try to find some time and contribute.

**Comment by mrlacey** [comment]
A period of illness has caused delays to my plans for porting extensions to VS2022. Hopefully I'll have a plan in the next few weeks

**Comment by SridharPasham** [comment]
This is working with VS2022. I love this extension. Thank you @mrlacey 👍 💯 🥇

**Comment by mrlacey** [comment]
The main version in the marketplace now supports VS2022.

If wanted, there's also [a separate version that works with VS2017 & 2019](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.CollapseComments2019)
