### ISSUE TITLE
Feature request: More collapse options

### ISSUE THREAD

**Issue by CA10C3SAR** [mrlacey/CollapseComments#19]
- Visual studio 2019.

Hello, mrlacey!

Would like to request two features, if possible.

1. A shortcut in which collapse everything less comments?
I know is possible to achieve it with CTRL+M, CTRL+O (collapse everything) then CTRL+M, CTRL+D (unfold comments), but would be better with just one shortcut.

2. Possibility to choose which comments will be folded, for example: `//` or `/* */`, or both.

I'm currently using the extension with `c++`.
Thank you for such useful extensions.

**Comment by mrlacey** [comment]
Sorry for the delayed response. Recent illness has stopped me working on anything but I hope to get to this eventually.

**Comment by CA10C3SAR** [comment]
Hello, hope you got better 🙏 
do you know if is possible somehow the feature 1

**Comment by mrlacey** [comment]
> Hello, hope you got better 🙏 do you know if is possible somehow the feature 1

noted. Will find some time to look at this shortly

**Comment by mrlacey** [comment]
> Hello, hope you got better 🙏 do you know if is possible somehow the feature 1

I've just published v2.2 which does this. :)
