### ISSUE TITLE
Feature: Include whitespace

### ISSUE THREAD

**Issue by Trevortni** [mrlacey/CollapseComments#20]
Would it be possible to include whitespace when collapsing comments?

So that 

`// Comment `
` `
`// More comments`
`// Still more comments`

would be able to collapse as one block? Maybe it would be worthwhile to retain sub-blocks for each section if desired, but it would be nice if comments separated only by whitespace would be able to combine at the very least.

**Comment by mrlacey** [comment]
These are currently detected by the existing language infrastructure. I'm not sure if it will be possible to change this. 
I think, according to the spec, (although it may vary by language) these are treated as separate comment blocks and so this could be confusing and hard to define what the actual behavior should be.

My first thought is "Treat consecutive comments as one."
But is that always what's wanted?

Given:

```csharp
\\ some comment

\\\ <summary>
\\\ Some details
\\\ </summary>
```

Does it make sense to combine these? - Maybe. maybe not. 🤷‍♀️

If I did this, it would be desirable **for me** to create something that is general and can be applied to multiple scenarios.
Based on the OP, it might provide more immediate benefit if this was only applied to C#-style multi-line comments.

I'm interested in other thoughts about how to take this forward....

**Comment by mrlacey** [comment]
I'm closing this as I can't change the current behavior and have had no other feedback.

Feel free to comment/reopen this if there is something I can do.

**Comment by Trevortni** [comment]
Sorry, I completely forgot I had posted this until I logged into github for a completely different project and saw the notification.

If there's nothing you can do, there's nothing you can do; however, to address your question about consecutive comments, I think my original (though perhaps not-so-obvious) suggestion of nesting collapses would apply, e.g.:


\+  +  // Some comments
  |   |_ // another line
  |
  |  + /// \<summary>
  |   | /// Some details
 |_ |_ /// \</summary>

Sorry about the formatting, it seems Markdown doesn't handled escaped list formatting inside code blocks very well.

**Comment by mrlacey** [comment]
Sadly, VS doesn't have the capability to easily control which region is expanded or collapsed when/if there are multiple regions starting on the same line (i.e. there would be multiple plus or minus signs beside each other to manually control what is expanded or collapsed. )
Sorry, this is a bit beyond me to build a custom workaround.

**Comment by Trevortni** [comment]
Thank you for your time and what is a nice tool even without this feature. I was just going to let it go at that and not bug you further, but before I could move on, I suddenly remembered that Visual Studio already has a pattern in place for handling nested collapse regions on the same line for inline functions passed as parameters to a function call, by cycling through the different options: from being open, it initially collapses everything, then it expands the function call, then it expands the inline function, and then it's back to collapsing everything again.

I don't know if that will help, and I appreciate that your time is valuable, but my OCD won't let me just not at least say something when a possible solution presents itself.
