### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by spacemonqi** [mrlacey/CollapseComments#22]
### Installed product versions
- Visual Studio: Version: 1.63.2 (Universal)
- This extension: Version | 2.0.1
- OS: MacOS Monterey 12.1

### Description
Using 'Install from VSIX' in VSCode yields "extension/package.json not found inside zip."

Any help would be much appreciated.

### Steps to recreate
1. Download the .vsix
2. Under 'Extensions' click 'Install from VSIX...' 

### Current behavior
No installation

### Expected behavior
Successful installation

**Comment by mrlacey** [comment]
This extension only supports Visual Studio (for Windows) and not VS Code. Sorry.

**Comment by spacemonqi** [comment]
I understand. Thanks for the reply!
