### ISSUE TITLE
Add the ability to collapse Attributes spread over multiple lines

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/CollapseComments#24]
As per the example below, the arguments for an attribute are spread over multiple lines and so take up lots of vertical space in the editor.

As the attribute (& arguments) aren't always important I'd like to be able to collapse them away.

![image](https://user-images.githubusercontent.com/189547/155122392-d6f4d68e-7d0f-4ed1-b0d0-647429735daa.png)

This should collapse to something like the following so it's still possible to see what the attribute is.

```cs
[SuppressMessage(...)]
```

**Comment by PeterHevesi** [comment]
+1 for this feature :)

**Comment by mrlacey** [comment]
![collapse-attributes](https://github.com/mrlacey/CollapseComments/assets/189547/c3d811fc-c95f-4c3c-9007-7539f7e2ea21)
coming soon

**Comment by mrlacey** [comment]
Released in version 2.5 - now available in the marketplace
