### ISSUE TITLE
[Feature Request] Fold active block

### ISSUE THREAD

**Issue by pepeu93** [mrlacey/CollapseComments#26]
- Visual Studio: 2022

Would like to request a hotkey to fold the currently active block, for example:

![image](https://user-images.githubusercontent.com/82878129/208802571-bfc6683b-dae9-470a-8500-50138c69be58.png)

When I have the caret in line **42** and press the hotkey it would fold only the content of

```c++
        for (int i = 0; i < sv.size(); i++)
        {
            eff = new GraphicsEffect(sv[i].blurRadius, sv[i].distance,
                sv[i].angle, sv[i].shadow_color);
            sv[i].widget->setGraphicsEffect(eff);
        }
```

When I have the caret in line `39` it would fold everything from line `38` to `46`

**Comment by mrlacey** [comment]
Nice idea. I'll see what I can do

**Comment by mrlacey** [comment]
This seems to go beyond the focus of the original intent of this extension which was just about working with comments.
Closing as I don't expect to ever add this.
