### ISSUE TITLE
console message driving me crazy

### ISSUE THREAD

**Issue by mishaxz** [mrlacey/CollapseComments#27]
this message is making me crazy.. I cannot tell what extension it belongs to, the link shows many. But I can't find any of those when i sort my installed extensions in VS.

**Please tell me what the name of it is** so I can uninstall it, thanks!

Show your support by making a one-off or recurring donation at https://github.com/sponsors/mrlacey

If you become a sponsor, I'll tell you how to hide this message too. ;)

**Comment by mrlacey** [comment]
Assuming it's not the one related to this repo,
It'll be one of these: https://marketplace.visualstudio.com/publishers/MattLaceyLtd

If that's the message you're seeing it's also a very old version of one of those extensions.

**Comment by mishaxz** [comment]
ok i figured out how to find it, i held the down arrow key down on installed extensions and kept an eye in the author box until it found matt lacey

it's the error helper, i copy and pasted the message from my output window. i'm not sure i'd call a month ago a very old version. it has auto update enabled.

**Comment by mrlacey** [comment]
> it's the error helper, i copy and pasted the message from my output window. i'm not sure i'd call a month ago a very old version. it has auto update enabled.

I thought I'd updated all those message to indicate where they came from. I guess I missed that one.
