### ISSUE TITLE
VS 17.4.5 Support

### ISSUE THREAD

**Issue by RaHorusFreak** [mrlacey/CollapseComments#28]
Nice work before all. I installed the extension in VS 17.4.5 and it's configurable from options panel, but it's invisible from contex menu, and the shortcut is assigned to schematization functions. Does the extension support recents VS releases?

**Comment by mrlacey** [comment]
Everything still works, it looks that for some reason (last September) I moved the menu form the Context menu on the editor to the Edit menu in the top-level menu.
I don't know why and can't find a reason for this.
Should I move it back?

**Comment by RaHorusFreak** [comment]
Hello Matt, I think that you should keep both options. I used your extension a lot in VS 16 versions, and honestly, it's faster and easier to do all ops from the context menu. Thanks in advance.

**Comment by mrlacey** [comment]
v2.3 addresses this and has just been published to the marketplace

**Comment by RaHorusFreak** [comment]
Works like charm!!!
