### ISSUE TITLE
Not collapsing on VS22 17.5.3

### ISSUE THREAD

**Issue by derricck** [mrlacey/CollapseComments#29]
In the doc it says:
> Ctrl+M, Ctrl+D expands all comments (and collapses everything else.)

When i press the shortcut its not collapsing anything, just expanding the comments.

Also, looks like after I installed the extension its causing any kind of conflict on the IDE, it now *randomly* starts unfolding collapsed blocks, have you experience this issue before?

I'm testing on Windows 10, and working on a `c++` project.

**Comment by mrlacey** [comment]
`Ctrl+M, Ctrl+D` is the default keybinding. If you already had something installed or configured to use that key combination then that might be the cause of what you're seeing.

If you go to **Tools > Options > Environment > Keyboard** you can see what command the key combination is bound to.

Being on Windows 10 shouldn't be an issue.
C++ has only had minimal testing and so might not correctly detect all types of comments. Do you have a repo (or files) I can use to test and to try and reproduce what you're seeing?

**Comment by mrlacey** [comment]
More info is needed to progress. 
Happy to reopen when more details available
