### ISSUE TITLE
Unexpected behavior of "Include using directive"

### ISSUE THREAD

**Issue by hiptopjones** [mrlacey/CollapseComments#34]
### Installed product versions
- Visual Studio: Community 2022 (64-bit) - Version 17.7.6
- This extension: v2.5

### Description
Unchecking "Include using directives" works with Ctrl-M, Ctrl-C, but not with "Run when document opened"

### Steps to recreate
1. Close all files
2. Open Options, navigate to Collapse Comments
3. Set "Include using directives" to false
4. Set "Run when document opened" to true
5. Apply and close options
6. Open a C# file

### Current behavior
All comment blocks and using blocks will be collapsed
Further, expanding with Ctrl-M,Ctrl-D does not expand the using blocks

### Expected behavior
All comment blocks will be collapsed, but using blocks stay expanded

**Comment by mrlacey** [comment]
I'm confused about your use of the term "using block". 
If you mean a "using **statement**" this is different from a "using **directive**" 

A "[using statement](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/using)" is for working with objects that implement `IDisposible`. 

e.g.

```cs
using (StreamReader reader = File.OpenText("somefile.txt"))
{
    // ...
}
```

A "[using directive](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive)"  is used to reference the types in a namespace without needing to qualify them fully.

e.g.

```cs
using System.Text;
```

This feature was introduced before global and implicit usings existed and it was common for C# files to start with many lines of using directives. As these lines would rarely change, the ability to collapse the using directives when opening a file was useful as it made it quicker/easier to get to the code that you actually wanted to see.


**However,** if the above is nothing new to you and using directives aren't being collapsed for you, please can you share a file (or repo) with code that will allow me to recreate what you're seeing. It's possible that you may have a sequence of lines containing using directives that aren't being detected/handled correctly.

**Comment by hiptopjones** [comment]
I apologize for my imprecise language and the resulting confusion.  I'm referring to the block of using directives at the top of the file.  I am now finding I cannot reproduce the problem because "Run when document opened" isn't working.  I am writing this off as something wrong with my install.  I will update or open a new issue if I figure it out.

**Comment by mrlacey** [comment]
Sadly, "Run when document opened" has never been 100% reliable. If you find a repro, please share.

**Comment by mrlacey** [comment]
>  I am writing this off as something wrong with my install. I will update or open a new issue if I figure it out.
