### ISSUE TITLE
Enhancement: Collapsed comment should remove prefix /// <summary>

### ISSUE THREAD

**Issue by grantph** [mrlacey/CollapseComments#6]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 1.0

### Description
For better readability, collapsed comments should remove the prefix /// <summary>

This would make a collapsed comment consistent with the rendering of a collapsed #region section.

For example:
> #region My Region
> #endregion

collapses to
> [My Region]

Therefore

> /// \<summary\>
> /// My summary
> /// \</summary\>

should collapse to
> [My summary]

**Comment by grantph** [comment]
And BTW - nice job. Combined with GhostDoc this is making my docs much cleaner :)

**Comment by mrlacey** [comment]
At the moment I'm just using the built-in visualization of the collapsed section. 
Will need to review what would be involved in this. 

I built this tool to hide the comments when I'm not interested in them and just want to focus on the code, modifying them (or at least their display) has potentially wider implications that need researching first.

**Comment by mrlacey** [comment]
@grantph The text that is shown in the collapsed summary comment is provided by [Roslyn](https://github.com/dotnet/roslyn) I suggest you [raise an issue](https://github.com/dotnet/roslyn/issues/new) to propose changing it there.

I'm not aware of a way to override the behavior they provide
