### ISSUE TITLE
Automatically collapse on opening files

### ISSUE THREAD

**Issue by HighKo** [mrlacey/CollapseComments#9]
First, I love this extension. Thank you!

### Installed product versions
- Visual Studio: [2019 Professional]
- This extension: [latest]

### Description
I would like to option to automatically collapse all comments if I open a file. 

### Current behavior
On opening a file all comments are fully visible.

### Expected behavior
On opening a file all comments should already be collapsed.

**Comment by mrlacey** [comment]
@HighKo That's a great idea. I'll see if I can make it possible. :)

**Comment by mrlacey** [comment]
Version 1.2 is now available in the marketplace and includes this functionality.

![image](https://user-images.githubusercontent.com/189547/78245538-8a987e00-74df-11ea-912d-a109fafc3760.png)

As it's a change in functionality it is off by default, so turn on if you want.

**Comment by mrlacey** [comment]
@HighKo  If this is helpful, I'd really appreciate a [review](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.CollapseComments&ssr=false#review-details).

**Comment by HighKo** [comment]
Works like a charm. Thank you! I dropped a review :)
